package com.uysal.minikakademi.core.navigation

object AppRoute {
    const val SPLASH = "splash"
    const val WELCOME = "welcome"
    const val PARENT_START_GATE = "parent_start_gate"
    const val CHILD_PROFILE = "child_profile"
    const val LEARNING_LEVEL = "learning_level"
    const val AVATAR = "avatar"
    const val SOUND = "sound"
    const val THEME = "theme"
    const val PIN = "pin"
    const val SETUP_SUMMARY = "setup_summary"
    const val HOME = "home"
    const val LEARNING_PATH = "learning_path"
    const val LEARNING_PATH_PATTERN = "learning_path/{category}"
    const val TRACING_HOME = "tracing_home"
    const val TRACING_ACTIVITY_PATTERN = "tracing_activity/{activityId}"
    const val LITERACY_HOME = "literacy_home"
    const val LITERACY_LETTER_PATTERN = "literacy_letter/{curriculumId}"
    const val LITERACY_ACTIVITY_PATTERN = "literacy_activity/{activityId}"
    const val MATHEMATICS_HOME = "mathematics_home"
    const val MATHEMATICS_CATEGORY_PATTERN = "mathematics_category/{sequenceId}"
    const val MATHEMATICS_ACTIVITY_PATTERN = "mathematics_activity/{activityId}"
    const val PARENT_GATE = "parent_gate"
    const val PARENT_DASHBOARD = "parent_dashboard"
    const val PARENT_SETTINGS = "parent_settings"

    fun learningPath(category: String): String = "$LEARNING_PATH/$category"
    fun tracingActivity(activityId: String): String = "tracing_activity/$activityId"
    fun literacyLetter(curriculumId: String): String = "literacy_letter/$curriculumId"
    fun literacyActivity(activityId: String): String = "literacy_activity/$activityId"
    fun mathematicsCategory(sequenceId: String): String = "mathematics_category/$sequenceId"
    fun mathematicsActivity(activityId: String): String = "mathematics_activity/$activityId"
}
